### PR TITLE
[types] override `QTipOptions.events` to use our `QTipApi`

### PR DESCRIPTION
**Pull request by ArielTam**
this error was identified during a first pass of turning on `strictFunctionTypes` in layer's tsconfig file:

```
 | ERROR in /Users/arieltam/Documents/hi/frontend/packages/layer-plugin/app/content/components/PerformanceFeedback/Flags.tsx
 | 125:17 No overload matches this call.
 |   Overload 1 of 2, '(props: Readonly<SimpleTooltipProps>): SimpleTooltip', gave the following error.
 |     Type '(_event: any, api: QTipApi) => void' is not assignable to type 'EventApiFunc'.
 |       Types of parameters 'api' and 'api' are incompatible.
 |         Type 'Api' is missing the following properties from type 'QTipApi': rendered, id, elements
 |   Overload 2 of 2, '(props: SimpleTooltipProps, context?: any): SimpleTooltip', gave the following error.
 |     Type '(_event: any, api: QTipApi) => void' is not assignable to type 'EventApiFunc'.
 |     123 |             },
 |     124 |             events: {
 |   > 125 |                 render: (_event: any, api: QTipApi) => {
 |         |                 ^
 |     126 |                     if (api.elements && api.elements.content) {
 |     127 |                         // This follows the patterns from PhraseTooltip and lets us render
 |     128 |                         // React content into the Tooltip.
```

in the past, we extended the `QTip2.Api` type to include a few of our own properties like `elements` -- this new type was named `QTipApi`. 

```
    export interface QTipApi extends QTip2.Api {
        rendered: boolean;
        id: string;
        elements: ApiElements;
    }
```

sometimes typescript would complain that `elements` (which is in `QTipApi`, but not in `QTip2.Api`) didn't exist, so we were always checking `if (api.elements && ...)`. 

after we turned on `strictFunctionTypes` in layer's tsconfig, we learned the root issue was that `QTipOptions`'s `render` was still using the original `QTip2.Api` type.  🤯  instead, it needed to use our `QTipApi` type, that way we had explicit access to `elements`.

it turned out that `render` was not the _only_ method that needed updating. all the `events` in `QTipOptions` are typed the same, with `EventApiFunc` referencing `QTip2.Api` instead of our `QTipApi`. this is why they are all included in the new `QTipApiEvents` type, which extends `QTip2.QTipOptions.Events`, however in the frontend repo, we only ever use `render`, `show`, and `hide`.

### CODE REVIEW

**Review by LauraAddams — COMMENTED** [review]
Shout out to `strictFunctionTypes`, nice catch Ariel!

👋🏻 Textio

**Review by adamsanderson — APPROVED** [review]
Seems fine to me!

FWIW: With an interface we should just be able to redefine it without exporting a new interface.

For example this _should_ work:

```
interface QTip2.QTipOptions.Events {
  render?: … ;
  show?: … ;
}
```

More [docs here](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation).

That said, if this gets us better typing today, go for it!

**Comment by ArielTam** [comment]
ohh it didn't occur to me that we could just redefine the interface. i think that looks a lot cleaner. i'll try it out!

edit: @adamsanderson i'm getting typescript errors all over saying `'QTipOptions' only refers to a type, but is being used as a value here.` 😢  maybe there is a way to do it, but i'm not sure how. 

Screenshot 2023-03-23 at 4 30 42 PM

**Comment by ArielTam** [comment]
hello laura! 👋

**Comment by david-davidson** [comment]
hi Laura!! (hi Ariel and Adam!)

**Review by david-davidson — APPROVED** [review]
LGTM - thanks for helping track this down and stewarding the fix!

**Comment by david-davidson** [comment]
btw @LauraRobertson we were all just talking about how your emojis are still the best at Textio 🙌

**Comment by LauraAddams** [comment]
> btw @LauraRobertson we were all just talking about how your emojis are still the best at Textio 🙌

❤️ @david-davidson When I make some new ones I'll be sure to send them your way~ Hope everyone is thriving!

**Pull request merged**
